[package]
name = "digest"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Traits for cryptographic hash functions"
documentation = "https://docs.rs/digest"
repository = "https://github.com/RustCrypto/traits"
keywords = ["digest", "crypto", "hash"]

[dependencies]
generic-array = "0.8"

[features]
std = []
