[package]
name = "digest"
version = "0.6.0-rc1"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Digest trait for cryptographic hash functions"
documentation = "https://docs.rs/digest"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["digest", "crypto", "hash"]

[dependencies]
generic-array = "0.8"

[features]
std = []
