[package]
name = "block-cipher-trait"
version = "0.4.0-beta"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Trait for block cipher algorithms"
documentation = "https://docs.rs/block-cipher-trait"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "block-cipher", "trait"]

[dependencies]
generic-array = "0.8"
