[package]
name          = "signature"
description   = "Traits for cryptographic signature algorithms (e.g. ECDSA, Ed25519)"
version       = "1.0.0-pre.3" # Also update html_root_url in lib.rs when bumping this
authors       = ["RustCrypto Developers"]
license       = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/signature"
repository    = "https://github.com/RustCrypto/traits/tree/master/signature"
readme        = "README.md"
edition       = "2018"
keywords      = ["crypto", "ecdsa", "ed25519", "signature", "signing"]
categories    = ["cryptography", "no-std"]

[dependencies.digest]
version = "0.8"
optional = true
default-features = false

[dependencies.rand_core]
version = "0.5"
optional = true
default-features = false

[dependencies.signature_derive]
version = "= 1.0.0-pre.1"
optional = true
path = "signature_derive"

[dev-dependencies]
hex-literal = "0.2"
sha2 = { version = "0.8", default-features = false }

[features]
default = ["std"]
derive-preview = ["digest-preview", "signature_derive"]
digest-preview = ["digest"]
rand-preview = ["rand_core"]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
