name: signature

on:
  pull_request:
    paths:
      - "signature/**"
      - "Cargo.*"
  push:
    branches: master
    paths:
      - "signature/**"
      - "Cargo.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.rust }}
          override: true
      - working-directory: signature
        run: cargo build --no-default-features --release --target ${{ matrix.target }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
    - run: |
        cargo check --all-features
        cargo test --no-default-features
        cargo test
      working-directory: signature
